In [ ]:
## Booleon Indexing

In [2]:
data=np.random.randn(7,4)

NameError: name 'np' is not defined

In [3]:
import numbpy as np

ModuleNotFoundError: No module named 'numbpy'

In [4]:
import numb py as np

SyntaxError: invalid syntax (<ipython-input-4-d5207ebd112d>, line 1)

In [5]:
import numpy as np

In [7]:
data=np.random.randn(7,4)
data

array([[ 0.97694697, -1.02140818,  0.05330818, -1.43957367],
       [-0.18918904,  0.3197645 , -0.40481863,  1.24230598],
       [ 0.15515894, -0.6370399 , -0.73109521, -1.27216951],
       [-1.56615826, -0.73027524, -0.02077632, -0.10204043],
       [-1.48900596,  1.32041552, -0.54410122,  0.66394878],
       [ 1.58469021, -0.37319055,  0.07070916,  1.47234686],
       [ 0.28722673, -0.47900942, -0.98590988,  1.3836709 ]])

In [8]:
bol=np.array[True, False, False,False,False,  True,False ],dtype="bool"

ValueError: too many values to unpack (expected 2)

In [9]:
bol=np.array([True, False, False,False,False,  True,False ],dtype="bool")

In [10]:
data[bol]

array([[ 0.97694697, -1.02140818,  0.05330818, -1.43957367],
       [ 1.58469021, -0.37319055,  0.07070916,  1.47234686]])

In [11]:
names=np.array["Bob","Will","Joe","Smith","Joe","Bob"]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [25]:
names=np.array(["Bob","Will","Joe","Smith","Joe","Bob","Joe"])

In [26]:
condition=(names!="Bob")

In [27]:
condition

array([False,  True,  True,  True,  True, False,  True])

In [28]:
data=np.random.randn(7,4)
data

array([[-1.41796328,  0.46137973,  1.25666307,  0.42930025],
       [ 0.89921168,  0.0745446 ,  0.66147033, -0.80295018],
       [ 1.22104648,  0.22918972,  0.36642653, -0.68312713],
       [-0.35278379,  0.47106246, -0.54908512,  0.77307535],
       [-0.76320423, -0.41117349,  1.96790333, -0.28428096],
       [-0.91830616, -1.02931893, -0.86430749, -0.54433344],
       [-0.11656491, -1.8470784 ,  2.31907692, -0.41723792]])

In [29]:
data [condition]

array([[ 0.89921168,  0.0745446 ,  0.66147033, -0.80295018],
       [ 1.22104648,  0.22918972,  0.36642653, -0.68312713],
       [-0.35278379,  0.47106246, -0.54908512,  0.77307535],
       [-0.76320423, -0.41117349,  1.96790333, -0.28428096],
       [-0.11656491, -1.8470784 ,  2.31907692, -0.41723792]])

In [30]:
data [~condition]

array([[-1.41796328,  0.46137973,  1.25666307,  0.42930025],
       [-0.91830616, -1.02931893, -0.86430749, -0.54433344]])

In [48]:
data=np.arange(35).reshape(7,6)
print(data)
print(condition)
data[~condition, 1:3]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[False  True  True  True  True False  True]


array([[ 1,  2],
       [26, 27]])

In [37]:
cond= (names=="Bob") & (names=="Joe")

In [38]:
cond

array([False, False, False, False, False, False, False])

In [39]:
cond= (names=="Bob") | (names=="Joe")
cond

array([ True, False,  True, False,  True,  True,  True])

In [40]:
data[cond]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])