import numby as np

In [2]:
import numpy as np

In [5]:
arr1d= np.array ([44,55,66,77])

In [6]:
arr1d[2]

66

In [7]:
arr1d[1:2]

array([55])

In [23]:
arr2d=np.([[111,222,333],[444,555,666],[777,888,999]])

SyntaxError: invalid syntax (<ipython-input-23-f6d35470a234>, line 1)

In [22]:
arr2d[1][2]

666

In [18]:
arr2d[:2]

[[111, 222, 333], [444, 555, 666]]

In [19]:
arr2d[:2,1:]

TypeError: list indices must be integers or slices, not tuple

In [20]:
arr2d([:2,1:])

SyntaxError: invalid syntax (<ipython-input-20-7fcc51b58b50>, line 1)

In [43]:
arr3d=np.array([[[100,220,333],[444,555,666],[777,888,999]],[[1,2,3],[4,5,6],[6,7,8]]])

In [44]:
arr3d

array([[[100, 220, 333],
        [444, 555, 666],
        [777, 888, 999]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  6,   7,   8]]])

In [45]:
arr3d.shape

(2, 3, 3)

In [46]:
arr3d[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [47]:
arr3d[1]

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [48]:
arr3d[0][2]

array([777, 888, 999])

In [49]:
arr3d.ndim

3

In [50]:
arr3d[1][1]

array([4, 5, 6])

In [51]:
arr3d[1][1][0]

4

In [52]:
arr3d[1,1,0]

4

In [53]:
arr3d[:2]

array([[[100, 220, 333],
        [444, 555, 666],
        [777, 888, 999]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  6,   7,   8]]])

In [56]:
arr3d[0,:2]

array([[100, 220, 333],
       [444, 555, 666]])

In [55]:
arr3d[0,:2,1:]

array([[220, 333],
       [555, 666]])

In [59]:
arr22d=([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,2],[7,5,1,6,5],[8,2,4,9,7]])

In [61]:
arr22d

[[2, 4, 6, 8, 10],
 [1, 2, 3, 4, 5],
 [4, 0, 6, 2, 5],
 [6, 6, 1, 5, 2],
 [7, 5, 1, 6, 5],
 [8, 2, 4, 9, 7]]

In [63]:
arr22d[2:4][2:]

[]

In [64]:
arr22d[2:4][2:]

[]

In [68]:
arr21=np.arange(36).reshape(6,6)

In [69]:
arr21

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [70]:
arr21[2:3][3:2]

array([], shape=(0, 6), dtype=int32)

In [71]:
arr21[2,3]

15

In [72]:
arr21[2,3:5]

array([15, 16])

In [73]:
arr21[2,3:5][3,3:]

IndexError: too many indices for array

In [74]:
arr21[2,3:5][3,3;]

SyntaxError: invalid syntax (<ipython-input-74-96be73a144b2>, line 1)

In [ ]:
#arr[row,coloumn]

In [75]:
arr21[2:3,0:6]

array([[12, 13, 14, 15, 16, 17]])

In [77]:
arr21[4:5,0:6]

array([[24, 25, 26, 27, 28, 29]])

In [78]:
arr21[3:4]

array([[18, 19, 20, 21, 22, 23]])

In [79]:
arr21[4:5]

array([[24, 25, 26, 27, 28, 29]])

In [80]:
arr21[,2]

SyntaxError: invalid syntax (<ipython-input-80-69ac7358700b>, line 1)

In [81]:
arr21[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [ ]:
# to show all row must be with colon

In [86]:
arr21[1:5]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [83]:
arr21[2:4,5]

array([17, 23])

In [84]:
arr21[2:4,4:5,3:2]

IndexError: too many indices for array

In [85]:
arr21[2:4,4;5,3;2]

SyntaxError: invalid syntax (<ipython-input-85-fbbece9e7db2>, line 1)

In [ ]:
arr21[2:4,4:5,3:2]

In [87]:
arr21[2:5,5:]

array([[17],
       [23],
       [29]])

In [88]:
arr21[:,:,-1]

IndexError: too many indices for array

In [89]:
arr21[:,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34]])

In [91]:
arr21[:,::-2]

array([[ 5,  3,  1],
       [11,  9,  7],
       [17, 15, 13],
       [23, 21, 19],
       [29, 27, 25],
       [35, 33, 31]])

In [92]:
arr21[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [93]:
arr21[1:3,::-2]

array([[11,  9,  7],
       [17, 15, 13]])

In [94]:
arr21[::2,::-2]

array([[ 5,  3,  1],
       [17, 15, 13],
       [29, 27, 25]])

In [95]:
arr21[0:5:2,0:5:-2]

array([], shape=(3, 0), dtype=int32)

In [96]:
arr21[0:5:2,-1::-2]

array([[ 5,  3,  1],
       [17, 15, 13],
       [29, 27, 25]])