In [1]:
arr=np.empty((8,4))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [5]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [6]:
arr[[4,0,1,7]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [7]:
arr[[4,0,1,7],[2,3,7,8]]

IndexError: index 7 is out of bounds for axis 1 with size 4

In [8]:
arr[[4,0,1,7],[2,3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (2,) 

In [16]:
arr=np.arange(32).reshape(8,4)
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [17]:
arr[[1,5,7,2]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [18]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [19]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [22]:
   aset={22,33,44,55,66,77}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

AttributeError: 'set' object has no attribute 'unique'

In [24]:
arr1=([[1,2,3,4],[6,7,8,9]])
arr2=([[77,99,33,22],[678,982,321,66]])

In [25]:
np.stack([arr1,arr2])

array([[[  1,   2,   3,   4],
        [  6,   7,   8,   9]],

       [[ 77,  99,  33,  22],
        [678, 982, 321,  66]]])

In [26]:
np.vstack([arr1,arr2])

array([[  1,   2,   3,   4],
       [  6,   7,   8,   9],
       [ 77,  99,  33,  22],
       [678, 982, 321,  66]])

In [27]:
np.hstack([arr1,arr2])

array([[  1,   2,   3,   4,  77,  99,  33,  22],
       [  6,   7,   8,   9, 678, 982, 321,  66]])

In [29]:
np.concenate([arr1,arr2],x=0)

AttributeError: module 'numpy' has no attribute 'concenate'

In [32]:
arr=np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
np.vsplit(arr)

TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'

In [33]:
np.vsplit(arr,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [38]:
np.vsplit(arr,4)

ValueError: array split does not result in an equal division