In [1]:
[1,2,36,11,87,8]

[1, 2, 36, 11, 87, 8]

[i*3 for i in ]

In [3]:
for i*3 for i in 1


SyntaxError: invalid syntax (<ipython-input-3-6e6d065a7125>, line 1)

In [4]:
l=range(1000,.1,10000)

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
l=rangr(1000)


NameError: name 'rangr' is not defined

In [20]:
l=range(1000000)

In [23]:
%time for i in l:i*7 

Wall time: 208 ms


In [25]:
import numpy as np
    

In [26]:
x=np.arange(1000000)

In [21]:
#array homogenous, fixed size, 

In [27]:
%time x*7

Wall time: 2.99 ms


array([      0,       7,      14, ..., 6999979, 6999986, 6999993])

In [28]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.ones((2,4))*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [32]:
l=[8,8,96,0]

In [33]:
np.array(l)

array([ 8,  8, 96,  0])

In [34]:
np.arange(100,1,-1)


array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [40]:
np.arange(100,-2,-2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2,   0])

np.arange(99,0,-2)

In [46]:
np.arange(7,73,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [47]:
np.empty((7,7))

array([[8.10230313e-312, 1.71440779e-321, 0.00000000e+000,
        0.00000000e+000, 2.96481201e+222, 1.15998412e-028,
        2.44171989e+232],
       [8.00801729e+159, 1.49890087e-076, 1.05235777e-153,
        4.00272163e-057, 6.03105348e-154, 1.13386644e-095,
        2.36945493e-038],
       [1.05148318e-153, 6.79597098e-038, 4.07347735e+223,
        6.01347002e-154, 8.52782982e-096, 5.51681704e-048,
        1.05206472e-153],
       [8.20680070e-067, 6.03104204e-154, 1.03968428e-095,
        8.41799487e-053, 1.02441779e+136, 6.01347002e-154,
        1.37704197e-047],
       [6.03106475e-154, 7.58600821e-096, 1.95996719e-062,
        1.05177167e-153, 1.65170963e-076, 6.03108747e-154,
        9.45502120e-096],
       [6.01347002e-154, 2.99067253e-067, 1.05235322e-153,
        2.72824811e-057, 6.03105331e-154, 1.12947737e-095,
        6.01353879e-154],
       [1.05146952e-153, 2.18229367e-094, 3.98472821e+252,
        1.47289889e+179, 9.08367237e+223, 1.16466228e-028,
        9.11224760

In [51]:
x=np.ones((3,3)

SyntaxError: unexpected EOF while parsing (<ipython-input-51-a6954c8e1299>, line 1)

In [50]:
x.astype('int32')

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [52]:
x.dtype


dtype('int32')

In [54]:
x.shape

(1000000,)

In [55]:
x.astype

<function ndarray.astype>

In [56]:
x.astype('int32')

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [57]:
x.shape

(1000000,)

In [58]:
x.ndim

1

In [60]:
x=np.ones((4,5))

In [61]:
np.shape

<function numpy.shape(a)>

In [62]:
np.shape(x)

(4, 5)

In [63]:
x.ndim

2

In [1]:
import numpy as np

In [10]:
x=np.array([0,5,6,7,6])
x>0


array([False,  True,  True,  True,  True])

In [11]:
x[x>0]

array([5, 6, 7, 6])

In [13]:
name=np.array(["ali","sadaf","xyz"])

In [14]:
name

array(['ali', 'sadaf', 'xyz'], dtype='<U5')

marks=np.array([89,90,20])

In [19]:
marks=np.array([89,90,20])

In [21]:
name[marks>=60]

array(['ali', 'sadaf'], dtype='<U5')

In [30]:
fee=np.array(["Sumitted","not Submitted","not Submitted"])

In [31]:
name[fee =="not Submitted"]

array(['sadaf', 'xyz'], dtype='<U5')

In [32]:
name[0]

'ali'

In [34]:
name[0:3]

array(['ali', 'sadaf', 'xyz'], dtype='<U5')

In [38]:
matrix=np.zeros([10,10])

In [39]:
matrix[1,1]=np.ones

TypeError: float() argument must be a string or a number, not 'function'

In [41]:
matrix[0:0]=1

In [42]:
matrix[

In [43]:
matrix[9:0]=1

In [45]:
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
matrix[1,1]=np.ones
matrix[:,0]=1

TypeError: float() argument must be a string or a number, not 'function'

In [47]:
matrix[1,1]=np.ones
matrix[:,0]=1

TypeError: float() argument must be a string or a number, not 'function'

In [49]:
x=np.ones([10,10])

In [50]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
x[1:-1,1:-1]=0

In [53]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
x=np.array[]

SyntaxError: invalid syntax (<ipython-input-54-63dbb1d67b03>, line 1)

In [55]:
x=np.ones([10,10])

In [81]:
x[2:1]=0

In [82]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])